### ISSUE TITLE
GPS FeatherWing I2C Issue on Feather M4 Express

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_FeatherWing#33]
During Regression Testings (See #32), I found a couple issues with the GPS FeatherWing that I'll elaborate some more about here:

GPS FeatherWing
Feather M4:	RuntimeError: SDA or SCL needs a pull up
nRF52840: 	Passed

On the Feather M4 Express, I get the following error:
```
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "/lib/adafruit_featherwing/gps_featherwing.py", line 36, in <module>
  File "/lib/adafruit_featherwing/shared.py", line 35, in <module>
RuntimeError: SDA or SCL needs a pull up
```

I'm sure this is caused by the fact that this uses a UART and not I2C, but I2C is initialized in the Shared Module. I need to figure a way around that. Most likely I will just not use shared.

I was running into a Waiting for Fix loop, but that seems to have sorted itself out, so it may just be related to the physical environment at the time I tested it. So I went ahead and changed that test to Passed on here.

**Comment by makermelissa** [comment]
Fixed #33 via #34.
